"""Compare our Dijkstra routes with OSRM and print a Markdown report.

For a seeded sample of origins across London, both engines route to nearby
charging stations. The report gives the ratio of our distances and times to
OSRM's, how often the two agree on which station is fastest, and query speed.

    docker compose exec -T backend python -m scripts.validate_road_graph > docs/road_graph_validation.md
"""

from __future__ import annotations

import random
import statistics
import time
from datetime import UTC, datetime

import numpy as np
from scipy.stats import spearmanr
from sqlalchemy import select

from app.database import SessionLocal
from app.dijkstra import get_road_graph
from app.geo import haversine_km
from app.models import Station
from app.routing_osrm import route_one_to_many

SEED = 7
ORIGINS = 200
STATIONS_PER_ORIGIN = 12
MAX_STRAIGHT_LINE_KM = 10.0
LAT_RANGE, LON_RANGE = (51.40, 51.62), (-0.30, 0.10)


def percentile(values: list[float], q: float) -> float:
    return float(np.percentile(values, q))


def main() -> None:
    rng = random.Random(SEED)
    with SessionLocal() as db:
        stations = [(s.lat, s.lon) for s in db.scalars(select(Station))]
    if not stations:
        raise SystemExit("No stations in the database. Run the ingest script first.")

    graph = get_road_graph()
    distance_ratio, time_ratio, rank_corr, query_ms = [], [], [], []
    same_fastest = compared = 0

    while compared < ORIGINS:
        origin = (rng.uniform(*LAT_RANGE), rng.uniform(*LON_RANGE))
        nearby = [s for s in stations if haversine_km(*origin, *s) <= MAX_STRAIGHT_LINE_KM]
        if len(nearby) < STATIONS_PER_ORIGIN:
            continue
        sample = rng.sample(nearby, STATIONS_PER_ORIGIN)

        osrm = route_one_to_many(origin_lat=origin[0], origin_lon=origin[1], destinations=sample)
        if osrm is None:
            raise SystemExit("OSRM is not responding. Start it with `docker compose up -d osrm`.")
        started = time.perf_counter()
        ours = graph.fastest_routes(origin, sample)
        query_ms.append((time.perf_counter() - started) * 1000)

        pairs = [(o, r) for o, r in zip(ours, osrm, strict=True) if o and np.isfinite(r.duration_min)]
        if len(pairs) < 3:
            continue
        compared += 1
        for o, r in pairs:
            distance_ratio.append(o.distance_km / r.distance_km)
            time_ratio.append(o.duration_min / r.duration_min)
        our_times = [o.duration_min for o, _ in pairs]
        osrm_times = [r.duration_min for _, r in pairs]
        rank_corr.append(spearmanr(our_times, osrm_times).statistic)
        same_fastest += int(np.argmin(our_times) == np.argmin(osrm_times))

    rows = [
        ("Our distance / OSRM distance", distance_ratio),
        ("Our drive time / OSRM drive time", time_ratio),
    ]
    table = "\n".join(
        f"| {label} | {statistics.median(v):.3f} | {percentile(v, 10):.3f} | {percentile(v, 90):.3f} |"
        for label, v in rows
    )
    print(
        f"""# Road graph validation

Generated by `scripts/validate_road_graph.py` on {datetime.now(UTC):%Y-%m-%d}. It compares the
fastest routes found by our Dijkstra search (`app/dijkstra.py`) with OSRM, both built from
the same OpenStreetMap snapshot, over {compared} random origins in Greater London and
{len(distance_ratio)} origin-to-station routes of up to {MAX_STRAIGHT_LINE_KM:.0f} km in a straight line.

| Measure | Median | 10th percentile | 90th percentile |
| --- | --- | --- | --- |
{table}

- **Same fastest station:** both engines pick the same one of the {STATIONS_PER_ORIGIN} candidates
  for {same_fastest / compared:.0%} of origins.
- **Rank agreement:** median Spearman correlation of {statistics.median(rank_corr):.3f} between
  the two engines' orderings of the candidates by drive time.
- **Query time:** {statistics.median(query_ms):.0f} ms median, {percentile(query_ms, 90):.0f} ms at the
  90th percentile, for one origin to {STATIONS_PER_ORIGIN} stations in pure Python.

## Reading the numbers

Distances agree closely because both engines walk the same streets. Our drive times come out
lower than OSRM's because our model is deliberately simple: free-flow speed on every road,
with no penalty for turning or for traffic signals. That makes absolute times optimistic, but
the ordering of stations, which is all the strategy uses, is what the rank agreement measures.
""",
        end="",
    )


if __name__ == "__main__":
    main()
